# Generated by Django 4.2.30 on 2026-07-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='is_verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
