# Generated by Django 4.2.30 on 2026-07-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_reviewrating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
