# Generated by Django 4.2.30 on 2026-07-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
