# Generated by Django 4.2.30 on 2026-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(help_text='Enter the name of the payment method (e.g., JazzCash)', max_length=100, unique=True)),
                ('method_logo', models.ImageField(blank=True, null=True, upload_to='payment_methods/logos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('account_qr_code', models.ImageField(blank=True, null=True, upload_to='payment_methods/qr_codes/')),
                ('instructions', models.TextField(blank=True, help_text='Enter any specific instructions for this payment method.', null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
