# Generated by Django 4.2.30 on 2026-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Enter any specific instructions for this payment method.'),
            preserve_default=False,
        ),
    ]
