# Generated by Django 4.2.30 on 2026-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_estimated_delivery_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
